services:
  postgres-1:
      image: postgres:16.6
      container_name: postgres-1
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgresdb
        PGDATA: /data
      volumes:
      - ./postgres-1/pgdata:/data
      - ./postgres-1/config:/config
      - ./postgres-1/archive:/mnt/server/archive
      command: postgres -c 'config_file=/config/postgresql.conf'
      ports:
      - "5432:5432"
      networks:
          - postgres
  postgres-2:
        image: postgres:16.6
        container_name: postgres-2
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgresdb
            PGDATA: /data
        volumes:
        - ./postgres-2/pgdata:/data
        - ./postgres-2/config:/config
        - ./postgres-2/archive:/mnt/server/archive
        command: postgres -c 'config_file=/config/postgresql.conf'
        ports:
        - "5433:5432"
        networks:
            - postgres
  postgres-3:
    image: postgres:16.6
    container_name: postgres-3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
      PGDATA: /data
    volumes:
      - ./postgres-3/pgdata:/data
      - ./postgres-3/config:/config
      - ./postgres-3/archive:/mnt/server/archive
    command: postgres -c 'config_file=/config/postgresql.conf'
    ports:
      - "5434:5432"
    networks:
      - postgres

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - postgres
networks:
    postgres:
        external: true